### ISSUE TITLE
Missing chaining method for VoidResult

### ISSUE THREAD

**Issue by CodeWizArt** [gorandalum/fluent-result#1]
Hi there, 

I am trying to adopt the fluent-result library to my code b/c I like the idea behind it. However, I am missing a method, at least for VoidResult. I would really like to pass a function to a method in success state.

What I am trying to achieve is that I can do another operation on my object and return the result.

E.g.
``` 
VoidResult<Foo> a(Bar bar) {
...
}
VoidResult<Foo> b(Bar bar) {
...
}

return a(bar)
    .map(b(bar));
``` 

so in case `a` succeeds I want to execute `b` and return the result of `b`. But I can't find a way to achieve this and and there's also no workaround like `ifSuccess`. 

Maybe I am overlooking something. Can you please give me a hint?

Thanks!

**Comment by gorandalum** [comment]
There is no `map` function since there is no value to apply the mapping on, so for `VoidResult` there is instead a [`replace`](https://gorandalum.github.io/fluent-result/no/gorandalum/fluentresult/VoidResult.html#replace(java.util.function.Supplier)) function. Take a look at that and see if it fits your need, and if it doesn't then reopen this issue.

**Comment by CodeWizArt** [comment]
Thanks for the quick response. `flatReplaceToVoidResult` did the trick for me! Not sure why I didn't see it myself.
